openapi: 3.1.2
info:
  title: Aces API
  version: 1.0.0

paths:
  /auth/refresh_session:
    $ref: './api/auth/openapi.yaml#/paths/~1auth~1refresh_session'
  /auth/send_otp:
    $ref: './api/auth/openapi.yaml#/paths/~1auth~1send_otp'